---
- name: Configure SSH for Radius Authentication
  hosts: docker-services
  gather_facts: true
  become: true
  become_method: sudo

  tasks:
    - name: Install libpam-radius-auth
      apt:
        name: libpam-radius-auth
        state: present

    - name: Modify sudo group line for passwordless access
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
        state: present

    - name: Ensure UsePAM yes is present and uncommented
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?UsePAM'
        line: 'UsePAM yes'
        state: present

    - name: Ensure ChallengeResponseAuthentication yes is present and uncommented or added
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication yes'
        state: present

    - name: Ensure pam_radius_auth.so is at the top of /etc/pam.d/sshd
      lineinfile:
        path: /etc/pam.d/sshd
        line: 'auth  sufficient   pam_radius_auth.so'
        insertbefore: BOF

    - name: Read the file content
      command: cat /etc/pam_radius_auth.conf
      register: file_content

    - name: Comment all lines in the file
      copy:
        dest: /etc/pam_radius_auth.conf
        content: |
          {% for line in file_content.stdout_lines %}
          # {{ line }}
          {% endfor %}
      when: file_content.stdout is defined

    - name: Insert Radius server configuration in pam_radius_auth.conf
      blockinfile:
        path: /etc/pam_radius_auth.conf
        insertafter: '^# server\[\:port\]\s+shared_secret\s+timeout\s+\(s\)\s+source_ip\s+vrf'
        block: |
          10.100.100.250:1812         linux123           60

    - name: Restart SSH service to apply changes
      service:
        name: ssh
        state: restarted